### ISSUE TITLE
Improving Documentation: Expanding current readme with some mandatory steps explained in Wiki

### ISSUE THREAD

**Issue by carmat88** [phnmnl/cloud-deploy-kubenow#53]
As correctly explained in the [phnmnl wiki,](https://github.com/phnmnl/phenomenal-h2020/wiki/Starting-a-PhenoMeNal-CRE-on-a-public-or-private-cloud-provider) it might be worthy to expand this readme a little bit so to give further details about some basic steps necessary to bootstrap Kubernetes

- Importing and sourcing RC file for OpenStack
- Start by creating your configuration file: config.aws.sh or config.ostack.sh or config.gce.sh 
- Touching upon the nova command while editing terraform script for Kubernetes bootstrap to get external uuid and flavor

**HINT:**
- nova network-list (to get external uuid)
- nova flavor-list

**Comment by andersla** [comment]
fixed by #55
